### ISSUE TITLE
Dataset Stats not Matching with Reported Stats in Paper

### ISSUE THREAD

**Issue by vaibhavad** [apple/ml-qrecc#1]
Hi,

Thanks for releasing the code and datasets of your [paper](https://arxiv.org/pdf/2010.04898.pdf). I downloaded the [data](https://github.com/apple/ml-qrecc/blob/main/dataset/qrecc_data.zip) and did some basic pre-processing. There seem to be some discrepancies in the stats of the dataset released and those reported in the paper.

Table 2 of the paper 51.4K questions and 8.7K dialogues in the train set. The released data has 63.5K questions and 10.8K dialogues. Are the train and dev set merged in the released dataset? The cumulative stats are also slightly different in the paper and released dataset - 81K questions and 13.7K dialogues reported in the paper and  80K questions and 13.6K dialogues in the released dataset. Is it due to some dataset cleaning after the paper was posted?

**Comment by RavitejaAnantha** [comment]
Hi -- Yes, the train and dev sets are merged. The (relative) minor difference in cumulative stats is because we rounded those to report in the paper.
