### ISSUE TITLE
About rewritten question

### ISSUE THREAD

**Issue by duongkstn** [apple/ml-qrecc#11]
Hi, 
There are many cases which rewritten question does not related to any previous context sentences. For example, in `qrecc_train.json`, at case of `"Conversation_no": 7135`, `"Turn_no": 4`:
```
{
        "Context": [
            "What is the change of course that is talked about in Huey Long's time as governor?",
            "Long announced his intention to run for the U.S. Senate in the Democratic primary of September 9, 1930.",
            "Are there any other interesting aspects about the Huey Long article?",
            "Long portrayed his campaign as a referendum on his programs: if he won it was a sign the public supported his programs, and if he lost he promised to resign.",
            "Did Huey Long win the Senate seat in 1930?",
            "Long defeated incumbent Senator Joseph E. Ransdell, an Alexandria native from Lake Providence in East Carroll Parish."
        ],
        "Question": "Why did he decide to do this?",
        "Rewrite": "Why did Huey Long decide to complete most of his four years as governor, before his term in the Senate?",
        "Answer": "He declared that leaving the seat vacant for so long would not hurt Louisiana; with Ransdell as Senator, the seat was vacant anyway.\u201c",
        "Answer_URL": "https://en.wikipedia.org/wiki/Huey_Long#Change_of_course_(1930)",
        "Conversation_no": 7135,
        "Turn_no": 4,
        "Conversation_source": "quac"
    }

```

The rewritten question said `his four years as governor` but that information is not included in context. I am building a question rewriting module with `Context` and `Question` as inputs and `Rewrite` as output, what should I do ?

Please explain to me clearly,
Thanks,

**Comment by RavitejaAnantha** [comment]
Thanks for pointing this out, we noticed this and we have retained these data points in our training and evaluation. You could either:
[1] Exclude such data points from your train/test if you're only concerned with reference resolution problem, or;
[2] Retain them and see if your retrained model can retrieve knowledge and produce sentence in addition to reference resolution, like multi-tasking.
