### ISSUE TITLE
Plan to release QR modeling code

### ISSUE THREAD

**Issue by Huffon** [apple/ml-qrecc#3]
Is there any plan to release QR modeling code?
Want to check out Tranformer++ model detail :)
Thanks in advance, Awesome work !

**Comment by ellenmellon** [comment]
I am also wondering whether you plan to release the QR modeling code? If possible, would you plan to release the whole baseline from query rewriting to answer extraction. Thank you so much for your great work and releasing the data!

**Comment by tuzhucheng** [comment]
Hi, thanks for your interest in the work!

I checked with @RavitejaAnantha and there is no plan to open-source the QR modeling code. However, you may find more details about the QR model in section 4.1 of https://dl.acm.org/doi/pdf/10.1145/3437963.3441748.

I will provide an update on the plan to release the answer extraction baseline model / code after checking with @shayne-longpre and other folks within ~1 month. Stay tuned!
