### ISSUE TITLE
wikipedia data

### ISSUE THREAD

**Issue by seahou3e** [apple/ml-qrecc#6]
I saw instructions of retrieving CommonCrawl data, how to retrieve Wikipedia data mentioned in the paper? Thanks

**Comment by tuzhucheng** [comment]
Hi @seahou3e, apologies about the late response.

Looking at the paper, I'm not sure which sentence you are referring to for the Wikipedia data.

If you mean you want to select the Wikipedia data that's a subset of the Common Crawl collection, you can first generate the entire Common Crawl data following instructions at https://github.com/apple/ml-qrecc/tree/main/collection. Then, in the .jsonl files created, select Wikipedia pages by filtering on the `id` field of each JSON object, which has the url of the webpage as the prefix.

**Comment by seahou3e** [comment]
I see, thanks. Closing the issue.
