### ISSUE TITLE
Common Crawl URLs issue

### ISSUE THREAD

**Issue by akaysh** [apple/ml-qrecc#7]
Current Common Crawl URLs don't work for downloading (give 403 Forbidden). 
According to the Common Crawl Website you should use:
1. https://data.commoncrawl.org/crawl-data/CC-MAIN-2019-47/cc-index.paths.gz
2. https://data.commoncrawl.org/crawl-data/CC-MAIN-2019-47/wet.paths.gz

And for index URLs follow this:

> By simply adding either s3://commoncrawl/ or https://data.commoncrawl.org/ to each line, you end up with the S3 and HTTP paths respectively.

**Comment by tuzhucheng** [comment]
Hi @akaysh, thank you so much for creating the issue! The links have been updated with https://github.com/apple/ml-qrecc/commit/cf44d03cb6676f7414471cec509d4a6c6858b0d3.
